# Generated by Django 4.2.2 on 2023-06-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_capacity_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
