# Generated by Django 4.2.2 on 2023-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_capacity_remove_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
