# Generated by Django 4.2.2 on 2023-06-27 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_event_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', related_query_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
